name: Montara CI

on:
  pull_request:

jobs:
  montara:
    runs-on: ubuntu-latest
    steps:
      - name: Montara CI
        uses: montara-io/montara-ci@v1.0.20
        with:
          webhookUrl: ${{ secrets.MONTARA_WEBHOOK_URL }}
